name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Ejecutar el flujo de trabajo solo en la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Obtiene el código del repositorio

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}      # Secreto configurado en GitHub
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Cambia a la región de tu EC2

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}   # Clave privada SSH
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}       # Dirección IP pública EC2
        REMOTE_USER: ${{ secrets.REMOTE_USER }}       # Usuario SSH (e.g., ubuntu)
      with:
        source: ./  # Archivos locales
        target: /var/www/html/  # Directorio remoto
 

