name: Deploy to EC2

on:
  push:
    branches:
      - main  # Despliega cuando hay cambios en la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usa un contenedor Ubuntu para correr el job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Revisa el código del repositorio

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY}}  # Agrega tu clave privada en los Secrets de GitHub

      - name: Copy files to EC2 instance
        run: |
          scp -r ./path/to/your/files/* ec2-user@${{ secrets.EC2_HOST }}:/var/www/html  # Copia los archivos al servidor EC2

      - name: Restart Apache
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} "sudo systemctl restart httpd"  # Reinicia Apache para que tome los nuevos archivos
