name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Cambiar a la carpeta del sitio
          cd /var/www/html
          # Descargar los últimos cambios del repositorio
          sudo git pull origin master
          # Cambiar permisos si es necesario
          sudo chmod -R 755 /var/www/html
          # Reiniciar Apache para asegurar los cambios
          sudo systemctl restart httpd

 

